package es.flakiness.hiccup;

import android.net.Uri;

// TODO: Could be generated by AutoValue.
public class PlayTalkEvent {
    private Uri uri;
    private int lastPosition;

    public PlayTalkEvent(Uri uri, int lastPosition) {
        this.uri = uri;
        this.lastPosition = lastPosition;
    }

    public Uri getUri() {
        return uri;
    }
    public int getLastPosition() { return lastPosition; }
}
